name: Develop Upload

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
    - name: set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm install
    - name: Install dependencies
      run: npx ci
    - name: Install semantic-release extra plugins
      uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          semantic_version: 19.0.2
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            @semantic-release/exec
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Build Android Release
      run: flutter build appbundle
    - name: Install Publish Requirements
      if: steps.semantic.outputs.new_release_published == 'true'
      run: pip3 install -r publish/requirements.txt
    - name: Publish to Google Play Internal Channel
      env: 
        STORE_PASSWORD: ${{ secrets.PLAY_STORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.PLAY_STORE_ALIAS }}
      if: steps.semantic.outputs.new_release_published == 'true'
      run: python3 publish/publish_bundle_to_store.py com.ycagri.historical_restaurants build/app/outputs/bundle/release/*.aab internal publish/key.p12
    - name: Build IOS Release
      if: steps.semantic.outputs.new_release_published == 'true'
      run: flutter build ipa
    - name: Publish to Apple Store Connect
      if: steps.semantic.outputs.new_release_published == 'true'
      run: flutter build ipa
      run: xcrun altool --upload-app --type ios -f build/ios/ipa/*.ipa --apiKey ${{ secrets.APP_STORE_CONNECT_API_KEY }} --apiIssuer ${{ secrets.APP_STORE_CONNECT_API_ISSUER }}