name: Pull Request

on:
  pull_request:
    branches: [ develop ]

jobs:
  unittest:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
    - name: Run Unit Tests
      run: flutter test